### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by ralfz123** [thomvessies/progressive-web-apps-2021#4]
Give the images a (max) size, so they don't cover half the page.

Like so:

```css
img {
  max-size: 35rem;
}
```
